name: Build, Test and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Create Database
        run: touch ./database/database.sqlite
      - name: Create .env file
        run: cp .env.test .env
      - name: Install Composer dependencies
        run: composer install
      - name: Install NPM dependencies
        run: npm install
      - name: Run NPM build
        run: npm run build
      - name: Run migrations
        run: php artisan migrate
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}
            ./build.sh
